#!system/bin/sh

### Ext4 File-Systems optimization & instant-mount
busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier =0,nobh /system

busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,barrier=0,nobh /data

busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,barrier=0,nobh /cache
